### PR TITLE
Configure external IP address and port

### LINKED ISSUE #57: Make p2p listen address configurable
This is especially important in fixed locations like VPS's and when running with Docker. Docker networking broken now because of this.

Somewhat related to #52

### LINKED ISSUE #70: Make P2P port / NAT port mapping configurable

### PR DESCRIPTION
**Pull request by JaniAnttonen**
Fixes #57 
Fixes #70

### CODE REVIEW

File: p2p/options.go [hunk 1]
```diff
@@ -1,30 +1,55 @@
...
-	if p2p.Config.GetBool("p2p.options.enableAutoRelay") {
+	if p2p.Config.GetBool("p2p.enableAutoRelay") {
 		options = append(options, libp2p.EnableAutoRelay())
 	}
 
-	if p2p.Config.GetBool("p2p.options.enableNATPortMap") {
+	if p2p.Config.GetBool("p2p.enableNATPortMap") {
 		options = append(options, libp2p.NATPortMap())
+	} else {
+		multiaddrs := defaultListenAddrs(p2pPort)
```
Comment (KristianWahlroos) [inline p2p/options.go]: I would create functions for these.

File: p2p/options_test.go [hunk 2]
```diff
@@ -29,34 +28,34 @@ func readTestConfig() {
...
 	configOptions := p2pInstance.CreateOptions()
 	options := []libp2pConfig.Option{}
+
 	options = append(options, p2pInstance.initDHT())
 	options = append(options, libp2p.Identity(p2pInstance.privateKey))
 	options = append(options, libp2p.EnableRelay())
 	options = append(options, libp2p.EnableAutoRelay())
-	options = append(options, libp2p.NATPortMap())
-	assert.Equal(t, fmt.Sprintf("%v", configOptions), fmt.Sprintf("%v", options))
-	os.Setenv(optionsEnableDHT, "false")
```
Comment (KristianWahlroos) [inline p2p/options_test.go]: Where did this test went? I liked this test.

File: p2p/options.go (hunk 1 above)
Comment (JaniAnttonen) [reply p2p/options.go]: They are on the cusp of being somewhat ugly here, but I wouldn't separate them because they are so dependant on variables inside the method.
